# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Dire bonjour
#' 
#' @description Dire bonjour à la personne dont le prénom est donné
#'
#' @param prenom Une chaine de carateres contenant le prenom de la personne à qui dire bonjour
#' @return Une chaine de caracteres
#' @export
#'
#' @examples
#' library(clementclaustre)
#' #Comportement par défaut
#' dire_bonjour()
#' #Dire bonjour à Clément
#' dire_bonjour("Clément")
#'
dire_bonjour <- function(prenom = "toi") {
  result <- glue::glue("Bonjour, {prenom}")
  return(result)
}
