# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' pays
#'
#' Un jeu de données contenant des informations sur des pays
#'
#' @format data frame de 241 lignes et 6 colonnes
#' \describe{
#'   \item{ V1 }{  int }
#'   \item{ V2 }{  int }
#'   \item{ V3 }{  chr }
#'   \item{ V4 }{  chr }
#'   \item{ V5 }{  chr }   
#'   \item{ V6 }{  chr }
#' }
"pays"
